language: cpp
compiler:
  - clang
notifications:
  email: false
env:
  matrix: 
    - JULIAVERSION="julianightlies" 
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia git -y
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.init(); Pkg.clone("https://github.com/andrewcooke/IntModN.jl")'
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("CRC"))`); Pkg.pin("CRC"); Pkg.resolve();'
  - julia ~/.julia/CRC/tests/runtests.jl
